<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- Version Patch.Minor.Major --> 
    <Version>1.0.0.6</Version>
	<!-- Thay đổi khi thay đổi logic, phá vỡ logic cũ -->
	<AssemblyVersion>1.0.0.0</AssemblyVersion> 
	<!--version của bản build đang chạy, cấu trúc Patch.Minor.Major.Build-->
    <FileVersion>1.0.0.6</FileVersion>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Service\**" />
    <Page Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.3.2" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="ModernWPF" Version="1.4.6" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.5" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.18.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.9.0.20240103" />
    <PackageReference Include="OpenCvSharp4.WpfExtensions" Version="4.9.0.20240103" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\icon.ico" />
    <Resource Include="assets\Logo.png" />
    <None Update="Models\active.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
